development:
  collections:
    games:
      title: Games
      description: Featured game projects.
      projects:
        - living-orb
        - lifetime
        - tea-and-time
        - touch-me-together
        - new-retro-pong
        - final-countdown
        - feed-the-pigeons-instead
        - fesses
        - big-boom-bada-boom
        - catfight-royale
        - how-we-make-demos
        - bunt
        - flying-stock-exchange
        - alterpong
        - 5k-run-simulator
    media-art:
      title: Media art
      description: Featured media art project.
      projects:
        - those-who-leave
        - webfunge
        - shader-evolution
        - black-and-white
        - fuckjs
        - narkissos-2.0
    software:
      title: Software
      description: Featured software projects.
      projects:
        - shadertoy-exporter
        - architect.cpp
        - blender-html5-animations
        - blender-addon-registry
        - vinewall
        - rollstreams
    commissions:
      title: Commissions
      description: Featured commissioned projects.
      projects:
        - mario-rabbids-kingdom-battle
        - bidul
        - recreation
        - light-mood
        - just-dance-2016
        - just-dance-now
        - carlos-pardo
        - james-bang
  fqdn: http://koltes.digital
  home:
    video: https://www.youtube.com/embed/87J-JETBMgM
  default:
    description: Jonathan Giroux, Digital Media Artist, Software Engineer.
    image: /pages/about/jonathan-giroux.jpg
